In [1]:
import numpy as np

In [6]:
A1 = np.array([[4,2,5],[2,6,2],[6,1,2]])
A2 = np.array([[4,2,4],[2,6,2],[6,1,2]])
A3 = np.array([[4,2,5],[2,5,2],[6,1,2]])

A1,A2,A3

(array([[4, 2, 5],
        [2, 6, 2],
        [6, 1, 2]]),
 array([[4, 2, 4],
        [2, 6, 2],
        [6, 1, 2]]),
 array([[4, 2, 5],
        [2, 5, 2],
        [6, 1, 2]]))

In [23]:
eigenvalues1, eigenvectors1 = np.linalg.eig(A1)
eigenvalues2, eigenvectors2 = np.linalg.eig(A2)
eigenvalues3, eigenvectors3 = np.linalg.eig(A3)


In [35]:
sorted_indices1 = np.argsort(-eigenvalues1)
eigenvalues_sorted1 = eigenvalues1[sorted_indices1]
eigenvectors_sorted1 = eigenvectors1[:,sorted_indices1]

sorted_indices2 = np.argsort(-eigenvalues2)
eigenvalues_sorted2 = eigenvalues2[sorted_indices2]
eigenvectors_sorted2 = eigenvectors3[:,sorted_indices2]

sorted_indices3 = np.argsort(-eigenvalues3)
eigenvalues_sorted3 = eigenvalues3[sorted_indices3]
eigenvectors_sorted3 = eigenvectors3[:,sorted_indices3]

print(f" Eigen Values : {eigenvalues_sorted1} \n Eigen Vectors : {eigenvectors_sorted1}")
print(f" Eigen Values : {eigenvalues_sorted2} \n Eigen Vectors : {eigenvectors_sorted2}")
print(f" Eigen Values : {eigenvalues_sorted3} \n Eigen Vectors : {eigenvectors_sorted3}")


 Eigen Values : [10.0862564   4.45231344 -2.53856984] 
 Eigen Vectors : [[-0.62581291  0.3003003   0.59754478]
 [-0.56795402 -0.87594531  0.04752115]
 [-0.53458996  0.3775441  -0.80042612]]
 Eigen Values : [ 9.70953904  4.23567914 -1.94521818] 
 Eigen Vectors : [[-0.65457471  0.24809842  0.59624933]
 [-0.50287543 -0.90472019  0.05434002]
 [-0.56448937  0.34630702 -0.80095811]]
 Eigen Values : [ 9.84837399  3.68599053 -2.53436452] 
 Eigen Vectors : [[-0.65457471  0.24809842  0.59624933]
 [-0.50287543 -0.90472019  0.05434002]
 [-0.56448937  0.34630702 -0.80095811]]


In [40]:
def calculate_eigen(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    idx = np.argsort(-eigenvalues)
    eigenvalues_sort = eigenvalues[idx]
    eigenvectors_sort = eigenvectors[:,idx]
    return eigenvalues_sort, eigenvectors_sort

Q1 = np.array([[4,2,5],
               [2,6,2],
               [6,1,2]])

Q2 = np.array([[4,2,4],
               [2,6,2],
               [6,1,2]])
Q3 = np.array([[4,2,5],
               [2,5,2],
               [6,1,2]])

eigenvalues_sort, eigenvectors_sort = calculate_eigen(Q1)

print(f"Eigen Values (Sorted) :", eigenvalues_sort)
print(f"Eigen Vectors (Sorted) :", eigenvectors_sort)

Eigen Values (Sorted) : [10.0862564   4.45231344 -2.53856984]
Eigen Vectors (Sorted) : [[-0.62581291  0.3003003   0.59754478]
 [-0.56795402 -0.87594531  0.04752115]
 [-0.53458996  0.3775441  -0.80042612]]


In [41]:
eigenvalues_sort, eigenvectors_sort = calculate_eigen(Q2)
print(f"Eigen Values (Sorted) :", eigenvalues_sort)
print(f"Eigen Vectors (Sorted) :", eigenvectors_sort)

Eigen Values (Sorted) : [ 9.70953904  4.23567914 -1.94521818]
Eigen Vectors (Sorted) : [[-0.58779736  0.30479966  0.53902619]
 [-0.60592357 -0.84456255  0.07548528]
 [-0.53605121  0.44024001 -0.83889972]]


In [42]:
eigenvalues_sort, eigenvectors_sort = calculate_eigen(Q3)
print(f"Eigen Values (Sorted) :", eigenvalues_sort)
print(f"Eigen Vectors (Sorted) :", eigenvectors_sort)

Eigen Values (Sorted) : [ 9.84837399  3.68599053 -2.53436452]
Eigen Vectors (Sorted) : [[-0.65457471  0.24809842  0.59624933]
 [-0.50287543 -0.90472019  0.05434002]
 [-0.56448937  0.34630702 -0.80095811]]


In [45]:
def calculate_svd(matrix):
    U,s,V = np.linalg.svd(matrix)
    return U,s

Singular_values, Singular_vectors = calculate_svd(Q1)

print("Singular Values (analogous to sorted Eigenvalues):",Singular_values)
print("Singular Vectors (analogous to sorted Eigenvectors):\n",Singular_vectors)

Singular Values (analogous to sorted Eigenvalues): [[-0.63120267  0.20462184 -0.74813975]
 [-0.53521859 -0.81302618  0.22919313]
 [-0.56135928  0.54508562  0.62270171]]
Singular Vectors (analogous to sorted Eigenvectors):
 [10.12198556  4.65831859  2.41774198]


In [50]:
U,s,V = np.linalg.svd(Q1)

rank = np.sum(s> 1e-10)

print(rank)

print("SVD Eigen Values :", U)
print("SVD Eigen Vectors :", s)


3
SVD Eigen Values : [[-0.63120267  0.20462184 -0.74813975]
 [-0.53521859 -0.81302618  0.22919313]
 [-0.56135928  0.54508562  0.62270171]]
SVD Eigen Vectors : [10.12198556  4.65831859  2.41774198]


In [52]:
import pandas as pd
import os

In [53]:
folder = "D:\Tinu Project\Projects Files Excel"
file = "Electric Motor.csv"

folder_file = os.path.join(folder,file)
df = pd.read_csv(folder_file)

In [54]:
df.head()

u_q    coolant  stator_winding       u_d  stator_tooth  motor_speed  \
0 -0.450682  18.805172       19.086670 -0.350055     18.293219     0.002866   
1 -0.325737  18.818571       19.092390 -0.305803     18.294807     0.000257   
2 -0.440864  18.828770       19.089380 -0.372503     18.294094     0.002355   
3 -0.327026  18.835567       19.083031 -0.316199     18.292542     0.006105   
4 -0.471150  18.857033       19.082525 -0.332272     18.291428     0.003133   

        i_d       i_q         pm  stator_yoke    ambient    torque  profile_id  
0  0.004419  0.000328  24.554214    18.316547  19.850691  0.187101          17  
1  0.000606 -0.000785  24.538078    18.314955  19.850672  0.245417          17  
2  0.001290  0.000386  24.544693    18.326307  19.850657  0.176615          17  
3  0.000026  0.002046  24.554018    18.330833  19.850647  0.238303          17  
4 -0.064317  0.037184  24.565397    18.326662  19.850639  0.208197          17

In [57]:
# Calculate the Covariance Matrix :

covariance_matrix = np.cov(df.T)

em_eigenvalues, em_eigenvectors = np.linalg.eig(covariance_matrix)

sort_ind = np.argsort(-em_eigenvalues)
sort_eig_val = em_eigenvalues[sort_ind]
sort_eig_vect = em_eigenvectors[:,sort_ind]

print("Sorted Eigenvalues:\n", sort_eig_val)
print("\nSorted Eigenvectors:\n", sort_eig_vect)

Sorted Eigenvalues:
 [3.46205318e+06 1.74111778e+04 2.99103853e+03 1.61894320e+03
 1.23531639e+03 3.49533071e+02 2.68444021e+02 1.55346091e+02
 5.76891805e+01 1.26502191e+01 3.07794712e+00 1.89976046e+00
 3.24037621e-01]

Sorted Eigenvectors:
 [[ 1.62230466e-02  5.09313799e-02  4.45243212e-01 -3.57772825e-01
   1.29442605e-01 -2.00864962e-01  7.67295881e-01  7.26138424e-02
   1.38017665e-01 -1.17513463e-02  2.06691292e-02 -1.28114672e-02
  -1.92848075e-03]
 [ 1.39947573e-04  4.44844468e-02 -1.53701621e-01 -4.12416078e-01
  -3.06163640e-02  8.67259735e-02 -7.17692333e-02 -7.33762342e-01
   2.88204990e-01 -3.30958753e-02  3.91734826e-01  1.15122896e-02
  -1.20610906e-01]
 [ 6.66324302e-03 -2.82329843e-02 -3.77700185e-01 -3.13943725e-01
   4.57169281e-02 -3.42663107e-01  2.71124885e-02  2.56645042e-01
  -4.80562228e-01  5.99433004e-03  5.20398028e-01  6.82839879e-02
   2.55690835e-01]
 [-9.79070830e-03  3.90708792e-01  7.20086758e-02 -5.41049075e-02
   8.78720702e-01  1.59288801e-02 -2.46